name: query
description: >
  Search query parser to implement customized search.
  Supports boolean groups, field scopes, ranges, comparisons...
version: 2.0.0
homepage: https://github.com/isoos/query

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  archive: ^3.3.1
  bitcount: ^0.3.0
  fs_shim: ^2.0.3
  http: ^0.13.5
  petitparser: ^5.0.0
  protobuf: ^2.1.0
  tuple: ^2.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
